_target_: trainer.ignite_multiple_trainer.IgniteMultipleTrainer
_recursive_: False
model_name: 
optimizer:
  _target_: torch.optim.Adam
  lr: 1e-3
begin_seg: 0.
num_epochs: 45
batch_size: 48
save_path: checkpoints/
losses:
  il:
    _target_: losses.L1Loss
    loss_weight: 0.1
validation:
  batch_size: 24
  save_best: 'psnr'
  visualize: False
  freq: 5
  n_saved: 1
metrics:
  train:
    psnr:
      _target_: ignite.metrics.PSNR
      data_range: 1.0
    ssim:
      _target_: ignite.metrics.SSIM
      data_range: 1.0
  val:
    psnr:
      _target_: utils.customMetrics.CustomPSNR #ignite.metrics.PSNR
      data_range: 1.0
    ssim:
      _target_: utils.customMetrics.CustomSSIM #ignite.metrics.SSIM
      data_range: 1.0