# @package _group_
_target_: trainer.ignite_tester.IgniteTester
batch_size: 1
upscale_factor: 4
path_pretrained: C:\Users\eliton\Documents\ml\segsr\zoo\pretrained-segsr.pt
save_path: D:\_ml\segsr
savefig_mode: null
metrics:
  psnr:
    _target_: ignite.metrics.PSNR
    data_range: 1.0
  ssim:
    _target_: ignite.metrics.SSIM
    data_range: 1.0
  uqi:
    _target_: utils.customMetrics.UQI