# @package _group_
_target_: trainer.ignite_tester.IgniteTester
batch_size: 1
upscale_factor: 4
path_pretrained: C:\Users\eliton\Documents\ml\segsr\zoo\test.pt
save_path: C:\Users\eliton\Documents\ml\segsr\test