defaults:
  - hydra/launcher: joblib

mode: train
name: Test1
rank:
gpus: [0]
dist_type: ddp # or dp, for DataParallel
backend: 'nccl'

dataloader:
  train: 
    _target_: dataloaders.CGEODataset
    path_lr: D:\datasets\cgeo\lr
    path_hr: D:\datasets\cgeo\hr
    path_seg: D:\datasets\cgeo\annotation
  val:
    _target_: dataloaders.CGEODataset
    path_lr: D:\datasets\cgeo\lr
    path_hr: D:\datasets\cgeo\hr
    path_seg: D:\datasets\cgeo\annotation
  test:
    _target_: dataloaders.CGEODataset
    path_lr: C:\Users\eliton\Documents\ml\datasets\cgeoNew\512-4xdown-l1
    path_hr: C:\Users\eliton\Documents\ml\datasets\cgeoNew\512-l1
    path_seg: C:\Users\Eliton\Documents\master\unet\data\train\annotation
  batch_size: 1
  n_classes: &nclass 4
  weight_classes: &wclass [1.,1.,1.,1.]
  prefetch: 1
  num_workers: 1
  pin_memory: False
  drop_last: True
  shuffle: True
  augmentation:
    aug1: False

archs:
  netG:
    _target_: models.rrdb_arch.RRDBNet
    num_in_ch: 3
    num_out_ch: 3
    num_feat: 64
    num_block: 23
  netD:
    _target_: models.vgg_arch.VGG128
    num_in_ch: 3
    num_feat: 64
  netSeg:
    _target_: models.model_unet_resnet.UNetResNet
    n_classes: *nclass

trainer:
  _target_: trainer.default_trainer.DefaultTrainer
  optimizer:
    _target_: torch.optim.Adam
    lr: 1e-4
  scheduler:
    _target_: torch.optim.lr_scheduler.MultiStepLR
    milestones: [0,10]
    gamma: 0.9
  use_seg: True
  arch_enc: 'unet'
  use_pretrained_seg: True
  path_pretrained_seg: 'epochs/unet-resnet-100.pth'
  use_pretrained_sr: True
  path_pretrained_g: 'epochs/seg1-new-sr-only_g.pth'
  path_pretrained_d: 'epochs/seg1-new-sr-only_d.pth'
  begin_seg: 0.
  num_epochs: 20
  scheduler_milestones: [50,100,150,200]
  scheduler_gamma: 0.1
  batch_size: 4
  crop_size: 256
  upscale_factor: 4
  lr: 1e-3
  model_save_path: 'epochs/'
  model_name: 'teste_seg'
  use_aug: True
  save_best: 'psnr'
  losses: 
    il:
      _target_: losses.L1Loss
      loss_weight: 1.0
    adv:
      _target_: losses.GANLoss
      gan_type: 'vanilla'
      loss_weight: 1.0
    per:
      _target_: losses.PerceptualLoss
      layer_weights: {'conv5_4': 1}
      perceptual_weight: 1.0
    tv:
      _target_: losses.WeightedTVLoss
      loss_weight: 1.0
    seg:
      _target_: losses.SegLoss
      loss_weight: 1.0
      weight_classes: *wclass
  validation:
    visualize: True
    batch_size: 1
    freq: 10
    n_chunks: 3
  metrics:
    train:
    val:
      - psnr
      - ssim
    

test:
  batch_size: 1
  upscale_factor: 4
  path_encoder: 'epochs/200_noseg_encoder.pth'
  path_image: 'data/LR/2953-3-SO_1_LR.png'
  path_save: 'results/test'
  prefix_save: 'seg'

