# defaults:
#   - hydra/launcher: joblib

mode: train
name: Test1
gpus: [0]
backend: # nccl

dataloader:
  train: 
    _target_: dataloaders.CGEODatasetForSegTask
    path_lr: C:\Users\Eliton\Documents\master\segsr\data\v1\cgeoNew\train\lr
    path_hr: C:\Users\Eliton\Documents\master\segsr\data\v1\cgeoNew\train\hr
    path_seg: C:\Users\Eliton\Documents\master\segsr\data\v1\cgeoNew\train\seg
    augCfg: ${dataloader.augmentation}
  val:
    _target_: dataloaders.CGEODatasetForSegTask
    path_lr: C:\Users\Eliton\Documents\master\segsr\data\v1\cgeoNew\val\lr
    path_hr: C:\Users\Eliton\Documents\master\segsr\data\v1\cgeoNew\val\hr
    path_seg: C:\Users\Eliton\Documents\master\segsr\data\v1\cgeoNew\val\seg
  test:
    _target_: dataloaders.CGEODatasetForSegTask
    path_lr: C:\Users\Eliton\Documents\master\segsr\data\v1\cgeoNew\test\lr
    path_hr: C:\Users\Eliton\Documents\master\segsr\data\v1\cgeoNew\test\hr
    path_seg: C:\Users\Eliton\Documents\master\segsr\data\v1\cgeoNew\test\seg
  # batch_size: 1
  n_classes: &nclass 4
  weight_classes: &wclass [1.,1.,1.,1.,1.]
  prefetch: 1
  num_workers: 1
  pin_memory: False
  drop_last: True
  shuffle: True
  augmentation:
    randomCrop:
      _target_: albumentations.RandomCrop
      height: 256
      width: 256
    verticalFlip:
      _target_: albumentations.VerticalFlip
    horizontalFlip:
      _target_: albumentations.HorizontalFlip
    transpose:
      _target_: albumentations.Transpose
    randomRotate90:
      _target_: albumentations.RandomRotate90
    totensor:
      _target_: albumentations.pytorch.ToTensorV2

archs:
  netSeg:
    _target_: models.model_unet_resnet.UNetResNet
    n_classes: *nclass

trainer:
  _target_: trainer.ignite_trainer_seg.IgniteTrainerSeg
  optimizer:
    _target_: torch.optim.Adam
    lr: 1e-4
  scheduler:
    _target_: torch.optim.lr_scheduler.MultiStepLR
    milestones: [0,10]
    gamma: 0.9
  arch_enc: 'unet'
  use_pretrained_seg: True
  path_pretrained_seg: 'epochs/unet-resnet-100.pth'
  begin_seg: 0.
  num_epochs: 10
  batch_size: 4
  upscale_factor: 4
  save_path: outputs/${name}
  losses: 
    cee:
      _target_: torch.nn.CrossEntropyLoss
  validation:
    batch_size: 4
    save_best: acc
    visualize: True
    freq: 1
    n_saved: 3
  metrics:
    train:
      acc:
        _target_: ignite.metrics.Accuracy
    val:
      acc:
        _target_: ignite.metrics.Accuracy
      cm:
        _target_: ignite.metrics.confusion_matrix.ConfusionMatrix
        num_classes: *nclass
      iou:
        _target_: ignite.metrics.IoU
      cr:
        _target_: ignite.metrics.ClassificationReport
    

test:
  batch_size: 1
  upscale_factor: 4
  path_encoder: 'epochs/200_noseg_encoder.pth'
  path_image: 'data/LR/2953-3-SO_1_LR.png'
  path_save: 'results/test'
  prefix_save: 'seg'

