defaults:
  - dataloader: cgeo-server
  - trainer: sr-trainer
  - archs: sr

mode: train
name: Test1
gpus: [0,1,2]
backend: nccl

  # netSeg:
  #   _target_: models.model_unet.UNet
  #   n_class: ${dataloader.n_classes}
    

test:
  batch_size: 1
  upscale_factor: 4
  path_encoder: 'epochs/200_noseg_encoder.pth'
  path_image: 'data/LR/2953-3-SO_1_LR.png'
  path_save: 'results/test'
  prefix_save: 'seg'

