defaults:
  - _self_
  - dataloader: seg-cgeo-home
  - archs: seg-unet
  - trainer: seg-trainer
  - trainer/scheduler: multistep
  - tester: seg-tester

mode: train
name: seg
gpus: [0,1,2]
backend: nccl