DATASET:
  train_dir: 'data/train'
  val_dir: 'data/val'
  seg_dir: 'data/annotation'
  n_classes: 4

TRAIN:
  use_seg: True
  arch_enc: 'unet'
  use_pretrained_seg: True
  path_pretrained_seg: 'epochs/unet-resnet-100'
  use_pretrained_sr: True
  path_pretrained_sr: 'epochs/200_noseg'
  begin_seg: 0.
  num_epochs: 20
  batch_size: 8
  crop_size: 256
  upscale_factor: 4
  visualize: True
  model_save_path: 'epochs/'
  model_name: 'teste_seg'
  use_aug: True
  scheduler_milestones: [50,100,150,200]
  scheduler_gamma: 0.1

VAL:
  batch_size: 1
  n_rows: 3

TEST:
  batch_size: 1
  path_encoder: "epochs/"
