DATASET:
  train_dir: 'data/train'
  val_dir: 'data/val'
  seg_dir: 'data/annotation'
  n_classes: 5

TRAIN:
  use_seg: True
  arch_enc: 'unet'
  begin_seg: 0.7
  num_epochs: 25
  batch_size: 1
  crop_size: 256
  upscale_factor: 4
  visualize: True
  model_save_path: 'epochs/'
  model_name: '25_seg'

VAL:
  batch_size: 1
  n_rows: 3

TEST:
  batch_size: 1
  path_encoder: ""
