DATASET:
  type: 'CGEODataset'
  train_dir: 'C:\Users\eliton\Documents\ml\datasets\train'
  val_dir: 'C:\Users\eliton\Documents\ml\datasets\val'
  seg_dir: ''
  n_classes: 4
  weight_classes: [.1, .3, .3, .2]

ARCHS:
  netG:
    type: 'RRDBNet'
    num_in_ch: 3
    num_out_ch: 3
    num_feat: 64
    num_block: 23
  netD:
    type: 'VGG128'
    num_in_ch: 3
    num_feat: 64
  netSeg:
    type: 'UNet'

TRAIN:
  use_seg: False
  arch_enc: ''
  use_pretrained_seg: False
  path_pretrained_seg: 'epochs/unet-novo-dataset'
  use_pretrained_sr: False
  path_pretrained_sr: 'epochs/200_noseg'
  begin_seg: 0.
  num_epochs: 20
  scheduler_milestones: [50,100,150,200]
  scheduler_gamma: 0.5
  batch_size: 2
  crop_size: 256
  upscale_factor: 4
  lr: 1e-4
  model_save_path: 'epochs/exp1'
  model_name: 'seg1-new-sr-only'
  use_aug: False
  losses: 
    il: 1e-2
    adv: 5e-3
    per: 1.0
    tv: 2e-8
    seg: 1e-3

VAL:
  visualize: True
  batch_size: 1
  freq: 1
  n_chunks: 5

TEST:
  batch_size: 1
  upscale_factor: 4
  path_encoder: 'C:\\Users\\eliton\\Documents\\ml\\BasicSR\\experiments\\esrgan_train1\\models\\net_g_75000.pth'
  path_image: 'C:\\Users\\eliton\\Documents\\ml\\datasets\\train_lr\\2953-3-SO_0_HR.png'
  path_save: 'results/test1'
