train: 
  _target_: dataloaders.CGEODatasetForSegTask
  _recursive_: False
  path_hr: C:\Users\Eliton\Documents\master\segsr\data\v1\cgeoNew\train\hr
  path_seg: C:\Users\Eliton\Documents\master\segsr\data\v1\cgeoNew\train\seg
  augCfg:
    randomCrop:
      _target_: albumentations.RandomCrop
      height: 256
      width: 256
    verticalFlip:
      _target_: albumentations.VerticalFlip
    horizontalFlip:
      _target_: albumentations.HorizontalFlip
    transpose:
      _target_: albumentations.Transpose
    randomRotate90:
      _target_: albumentations.RandomRotate90
    totensor:
      _target_: albumentations.pytorch.ToTensorV2
val:
  _target_: dataloaders.CGEODatasetForSegTask
  path_hr: C:\Users\Eliton\Documents\master\segsr\data\v1\cgeoNew\val\hr
  path_seg: C:\Users\Eliton\Documents\master\segsr\data\v1\cgeoNew\val\seg
test:
  _target_: dataloaders.CGEODatasetForSegTask
  path_hr: C:\Users\Eliton\Documents\master\segsr\data\v1\cgeoNew\test\hr
  path_seg: C:\Users\Eliton\Documents\master\segsr\data\v1\cgeoNew\test\seg
n_classes: 5
weight_classes: [1.,1.,1.,1.,1.]
rgb_mean: [0.3151, 0.3444, 0.3060]
prefetch: 1
num_workers: 1
pin_memory: True
drop_last: True
shuffle: True